/**
 * Remix line icons with Lucide-compatible export names.
 * Import from here instead of lucide-react.
 */
import type { RemixiconComponentType, RemixiconProps } from '@remixicon/react'
import { RiLoader4Line } from '@remixicon/react'
import { cn } from '@/lib/utils'

export type RemixIcon = RemixiconComponentType
export type RemixIconProps = RemixiconProps

export function Loader2({ className, ...props }: RemixiconProps) {
  return <RiLoader4Line className={cn('animate-spin', className)} {...props} />
}

export { RiPulseLine as Activity } from '@remixicon/react'
export { RiErrorWarningLine as AlertCircle } from '@remixicon/react'
export { RiAlertLine as AlertTriangle } from '@remixicon/react'
export { RiArrowDownLine as ArrowDown } from '@remixicon/react'
export { RiArrowRightDownLine as ArrowDownRight } from '@remixicon/react'
export { RiSortDesc as ArrowDownWideNarrow } from '@remixicon/react'
export { RiArrowLeftLine as ArrowLeft } from '@remixicon/react'
export { RiArrowRightLine as ArrowRight } from '@remixicon/react'
export { RiArrowUpLine as ArrowUp } from '@remixicon/react'
export { RiArrowUpDownLine as ArrowUpDown } from '@remixicon/react'
export { RiSeoLine as SeoLine } from '@remixicon/react'
export { RiStore2Line as Store2Line } from '@remixicon/react'
export { RiSearchAiLine as SearchAiLine } from '@remixicon/react'
export { RiArrowRightUpLine as ArrowUpRight } from '@remixicon/react'
export { RiSortAsc as ArrowUpWideNarrow } from '@remixicon/react'
export { RiAwardLine as Award } from '@remixicon/react'
export { RiVerifiedBadgeLine as BadgeCheck } from '@remixicon/react'
export { RiZoomInLine as ZoomIn } from '@remixicon/react'
export { RiMoneyRupeeCircleLine as Banknote } from '@remixicon/react'
export { RiBarChartLine as BarChart2 } from '@remixicon/react'
export { RiBarChartGroupedLine as BarChart3 } from '@remixicon/react'
export { RiNotificationLine as Bell } from '@remixicon/react'
export { RiBookmarkLine as Bookmark } from '@remixicon/react'
export { RiBookmarkLine as BookmarkCheck } from '@remixicon/react'
export { RiBookmarkLine as BookMarked } from '@remixicon/react'
export { RiBookOpenLine as BookOpen } from '@remixicon/react'
export { RiRobot2Line as Bot } from '@remixicon/react'
export { RiStackLine as Boxes } from '@remixicon/react'
export { RiBrainLine as Brain } from '@remixicon/react'
export { RiBriefcaseLine as Briefcase } from '@remixicon/react'
export { RiBriefcaseLine as BriefcaseBusiness } from '@remixicon/react'
export { RiBugLine as Bug } from '@remixicon/react'
export { RiBuildingLine as Building2 } from '@remixicon/react'
export { RiCalculatorLine as Calculator } from '@remixicon/react'
export { RiCalendarLine as Calendar } from '@remixicon/react'
export { RiCalendarLine as CalendarDays } from '@remixicon/react'
export { RiCameraLine as Camera } from '@remixicon/react'
export { RiCheckLine as Check } from '@remixicon/react'
export { RiCheckboxCircleLine as CheckCircle2 } from '@remixicon/react'
export { RiArrowDownSLine as ChevronDown } from '@remixicon/react'
export { RiArrowLeftSLine as ChevronLeft } from '@remixicon/react'
export { RiArrowRightSLine as ChevronRight } from '@remixicon/react'
export { RiArrowUpSLine as ChevronUp } from '@remixicon/react'
export { RiCheckboxBlankCircleLine as Circle } from '@remixicon/react'
export { RiCheckboxCircleLine as CircleCheck } from '@remixicon/react'
export { RiRecordCircleLine as CircleDot } from '@remixicon/react'
export { RiQuestionLine as CircleHelp } from '@remixicon/react'
export { RiClipboardLine as ClipboardCheck } from '@remixicon/react'
export { RiClipboardLine as ClipboardList } from '@remixicon/react'
export { RiClipboardLine as Clipboard } from '@remixicon/react'
export { RiTimeLine as Clock } from '@remixicon/react'
export { RiCupLine as Coffee } from '@remixicon/react'
export { RiCoinLine as Coins } from '@remixicon/react'
export { RiCompass3Line as Compass } from '@remixicon/react'
export { RiFileCopyLine as Copy } from '@remixicon/react'
export { RiCpuLine as Cpu } from '@remixicon/react'
export { RiBankCardLine as CreditCard } from '@remixicon/react'
export { RiFocus3Line as Crosshair } from '@remixicon/react'
export { RiVipCrownLine as Crown } from '@remixicon/react'
export { RiDiamondLine as Diamond } from '@remixicon/react'
export { RiDatabase2Line as Database } from '@remixicon/react'
export { RiMoneyDollarCircleLine as DollarSign } from '@remixicon/react'
export { RiDownloadLine as Download } from '@remixicon/react'
export { RiExternalLinkLine as ExternalLink } from '@remixicon/react'
export { RiEyeLine as Eye } from '@remixicon/react'
export { RiEyeOffLine as EyeOff } from '@remixicon/react'
export { RiFacebookLine as Facebook } from '@remixicon/react'
export { RiBuilding2Line as Factory } from '@remixicon/react'
export { RiFileCheckLine as FileCheck } from '@remixicon/react'
export { RiFileCodeLine as FileJson } from '@remixicon/react'
export { RiFileExcelLine as FileSpreadsheet } from '@remixicon/react'
export { RiFileTextLine as FileText } from '@remixicon/react'
export { RiFileTextLine as FileTextIcon } from '@remixicon/react'
export { RiFilterLine as Filter } from '@remixicon/react'
export { RiFlagLine as Flag } from '@remixicon/react'
export { RiFireLine as Flame } from '@remixicon/react'
export { RiFlaskLine as FlaskConical } from '@remixicon/react'
export { RiFolderLine as Folder } from '@remixicon/react'
export { RiFolderOpenLine as FolderOpen } from '@remixicon/react'
export { RiDashboard3Line as Gauge } from '@remixicon/react'
export { RiGiftLine as Gift } from '@remixicon/react'
export { RiGitBranchLine as GitBranch } from '@remixicon/react'
export { RiGlobalLine as Globe } from '@remixicon/react'
export { RiGlobalLine as Globe2 } from '@remixicon/react'
export { RiGraduationCapLine as GraduationCap } from '@remixicon/react'
export { RiDraggable as GripVertical } from '@remixicon/react'
export { RiHammerLine as Hammer } from '@remixicon/react'
export { RiShakeHandsLine as Handshake } from '@remixicon/react'
export { RiHashtag as Hash } from '@remixicon/react'
export { RiHeartLine as Heart } from '@remixicon/react'
export { RiHeartPulseLine as HeartPulse } from '@remixicon/react'
export { RiQuestionLine as HelpCircle } from '@remixicon/react'
export { RiHistoryLine as History } from '@remixicon/react'
export { RiInboxLine as Inbox } from '@remixicon/react'
export { RiInformationLine as Info } from '@remixicon/react'
export { RiInstagramLine as Instagram } from '@remixicon/react'
export { RiKeyLine as KeyRound } from '@remixicon/react'
export { RiBankLine as Landmark } from '@remixicon/react'
export { RiStackLine as Layers } from '@remixicon/react'
export { RiDashboardLine as LayoutDashboard } from '@remixicon/react'
export { RiLayoutGridLine as LayoutGrid } from '@remixicon/react'
export { RiLayoutLeftLine as LayoutLeft } from '@remixicon/react'
export { RiLayoutRightLine as LayoutRight } from '@remixicon/react'
export { RiLeafLine as Leaf } from '@remixicon/react'
export { RiLifebuoyLine as LifeBuoy } from '@remixicon/react'
export { RiLightbulbLine as Lightbulb } from '@remixicon/react'
export { RiLightbulbLine as LightbulbIcon } from '@remixicon/react'
export { RiLineChartLine as LineChart } from '@remixicon/react'
export { RiLinksLine as Link2 } from '@remixicon/react'
export { RiLinkedinLine as Linkedin } from '@remixicon/react'
export { RiListCheck as List } from '@remixicon/react'
export { RiListCheck2 as ListChecks } from '@remixicon/react'
export { RiLockLine as Lock } from '@remixicon/react'
export { RiLogoutBoxRLine as LogOut } from '@remixicon/react'
export { RiMailLine as Mail } from '@remixicon/react'
export { RiMailAddLine as MailPlus } from '@remixicon/react'
export { RiMapLine as Map } from '@remixicon/react'
export { RiMapPinLine as MapPin } from '@remixicon/react'
export { RiFullscreenLine as Maximize2 } from '@remixicon/react'
export { RiFullscreenExitLine as Minimize2 } from '@remixicon/react'
export { RiMegaphoneLine as Megaphone } from '@remixicon/react'
export { RiMenuLine as Menu } from '@remixicon/react'
export { RiChat3Line as MessageCircle } from '@remixicon/react'
export { RiQuestionAnswerLine as MessageCircleQuestion } from '@remixicon/react'
export { RiChat1Line as MessageSquare } from '@remixicon/react'
export { RiChat1Line as MessageSquareText } from '@remixicon/react'
export { RiChatQuoteLine as MessageSquareWarning } from '@remixicon/react'
export { RiMicroscopeLine as Microscope } from '@remixicon/react'
export { RiSubtractLine as Minus } from '@remixicon/react'
export { RiComputerLine as Monitor } from '@remixicon/react'
export { RiDownloadLine as MonitorDown } from '@remixicon/react'
export { RiNewspaperLine as Newspaper } from '@remixicon/react'
export { RiBox3Line as Package } from '@remixicon/react'
export { RiSearchEyeLine as PackageSearch } from '@remixicon/react'
export { RiPlantLine as Palmtree } from '@remixicon/react'
export { RiPauseCircleLine as PauseCircle } from '@remixicon/react'
export { RiPencilLine as Pencil } from '@remixicon/react'
export { RiQuillPenLine as PenLine } from '@remixicon/react'
export { RiPercentLine as Percent } from '@remixicon/react'
export { RiPhoneLine as Phone } from '@remixicon/react'
export { RiPieChartLine as PieChart } from '@remixicon/react'
export { RiCoinLine as PiggyBank } from '@remixicon/react'
export { RiPlayLine as Play } from '@remixicon/react'
export { RiPlugLine as Plug } from '@remixicon/react'
export { RiAddLine as Plus } from '@remixicon/react'
export { RiDoubleQuotesL as Quote } from '@remixicon/react'
export { RiRadarLine as Radar } from '@remixicon/react'
export { RiRadioLine as Radio } from '@remixicon/react'
export { RiReceiptLine as Receipt } from '@remixicon/react'
export { RiRefreshLine as RefreshCw } from '@remixicon/react'
export { RiRepeatLine as Repeat } from '@remixicon/react'
export { RiRepeatLine as Repeat2 } from '@remixicon/react'
export { RiReplyLine as Reply } from '@remixicon/react'
export { RiRocketLine as Rocket } from '@remixicon/react'
export { RiScalesLine as Scale } from '@remixicon/react'
export { RiSearchLine as Search } from '@remixicon/react'
export { RiSearchLine as SearchIcon } from '@remixicon/react'
export { RiSendPlaneLine as Send } from '@remixicon/react'
export { RiSettings3Line as Settings } from '@remixicon/react'
export { RiSettings4Line as Settings2 } from '@remixicon/react'
export { RiSettings4Line as SettingsIcon } from '@remixicon/react'
export { RiShapesLine as Shapes } from '@remixicon/react'
export { RiShareLine as Share } from '@remixicon/react'
export { RiShareLine as Share2 } from '@remixicon/react'
export { RiShieldLine as Shield } from '@remixicon/react'
export { RiShieldFlashLine as ShieldAlert } from '@remixicon/react'
export { RiShieldCheckLine as ShieldCheck } from '@remixicon/react'
export { RiTShirtLine as Shirt } from '@remixicon/react'
export { RiShoppingBagLine as ShoppingBag } from '@remixicon/react'
export { RiShoppingCartLine as ShoppingCart } from '@remixicon/react'
export { RiSkullLine as Skull } from '@remixicon/react'
export { RiEqualizerLine as SlidersHorizontal } from '@remixicon/react'
export { RiSmartphoneLine as Smartphone } from '@remixicon/react'
export { RiSparklingLine as Sparkles } from '@remixicon/react'
export { RiStarLine as Star } from '@remixicon/react'
export { RiSwordLine as Swords } from '@remixicon/react'
export { RiPriceTag3Line as Tag } from '@remixicon/react'
export { RiFocus3Line as Target } from '@remixicon/react'
export { RiTimerLine as Timer } from '@remixicon/react'
export { RiDeleteBinLine as Trash2 } from '@remixicon/react'
export { RiArrowDownLine as TrendingDown } from '@remixicon/react'
export { RiArrowUpLine as TrendingUp } from '@remixicon/react'
export { RiTruckLine as Truck } from '@remixicon/react'
export { RiLockUnlockLine as Unlock } from '@remixicon/react'
export { RiUserLine as User } from '@remixicon/react'
export { RiUserFollowLine as UserCheck } from '@remixicon/react'
export { RiUserLine as UserCircle } from '@remixicon/react'
export { RiTimeLine as UserClock } from '@remixicon/react'
export { RiUserSettingsLine as UserCog } from '@remixicon/react'
export { RiUserAddLine as UserPlus } from '@remixicon/react'
export { RiUserLine as UserRound } from '@remixicon/react'
export { RiGroupLine as Users } from '@remixicon/react'
export { RiVideoLine as Video } from '@remixicon/react'
export { RiWalletLine as Wallet } from '@remixicon/react'
export { RiMagicLine as Wand2 } from '@remixicon/react'
export { RiRouteLine as Waypoints } from '@remixicon/react'
export { RiPlantLine as Wheat } from '@remixicon/react'
export { RiToolsLine as Wrench } from '@remixicon/react'
export { RiScan2Line as Scan2Line } from '@remixicon/react'
export { RiCloseLine as X } from '@remixicon/react'
export { RiCloseCircleLine as XCircle } from '@remixicon/react'
export { RiYoutubeLine as Youtube } from '@remixicon/react'
export { RiFlashlightLine as Zap } from '@remixicon/react'

import type { CSSProperties } from 'react'
import { CreditsIcon as PowerProofCreditsIcon } from '@/components/credits/CreditsIcon'

export { CreditsIcon, CreditsFigure } from '@/components/credits/CreditsIcon'

/** Filled credit coupon at marketing icon scale (pricing page, tours). */
export function CreditsCoupon({
  className,
  style,
}: {
  className?: string
  style?: CSSProperties
}) {
  return <PowerProofCreditsIcon size={28} className={className} />
}
