/**
 * Slim profile projection for auth context.
 * Keep in sync with public.profiles (verified against Supabase information_schema).
 */
export const PROFILE_SELECT = [
  'id',
  'email',
  'full_name',
  'username',
  'display_name',
  'bio',
  'avatar_url',
  'website',
  'location_city',
  'location_state',
  'employment_status',
  'phone',
  'city',
  'state',
  'onboarding_completed',
  'onboarding_step',
  'onboarding',
  'budget_range',
  'preferred_categories',
  'preferred_state',
  'home_country',
  'preferred_currency',
  'preferred_ai_model',
  'role',
  'referral_code',
  'referred_by_user_id',
  'notif_weekly_trending',
  'notif_saved_category',
  'notif_govt_alerts',
  'display_setup_cost',
  'display_description',
  'investors_list_unlocked_at',
  'created_at',
  'updated_at',
].join(', ')
