// admin-create-opportunity-v2
// Admin-only (profiles.role = admin|super_admin), triggered from Cursor.
// Input: { title_idea: string } — country hardcoded India, style hardcoded standard.
// Reuses research-opportunity v45's prompt structure + derivation math verbatim
// (deriveSetupCost/deriveProfitMargin/deriveEase/computeFitIndex/buildGovtSchemeDetails)
// so new rows are consistent with how every existing opportunity was generated.
// Writes the FULL schema (legacy fields + the 17 research-grade fields added in
// the additive migration) directly to public.opportunities as status='live'.
// score is NOT generated by the model — compute_opportunity_score(id) is called
// after insert, since score depends on live engagement data (views/saves) that
// a brand-new row cannot have yet. This mirrors how the function is designed to
// be used, even though nothing currently schedules it automatically.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.8'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-gemini-key',
}

function json(data, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
}

const GEMINI_MODEL = 'gemini-2.5-flash'
const GEMINI_TIMEOUT_MS = 140000

function slugify(t) {
  return t.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim().slice(0, 80)
}
function strip(s) {
  return s.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim()
}

// ---- Derivation math, copied verbatim from research-opportunity v45 ----

function deriveSetupCost(breakdown) {
  const items = breakdown.map((i) => ({ label: String(i.label ?? ''), amount_usd: Number(i.amount_usd ?? 0) }))
  const subtotal = items.reduce((s, i) => s + i.amount_usd, 0)
  const optimistic = Math.round(subtotal * 0.85)
  const buffer = Math.round(subtotal * 1.2)
  const topItems = [...items].sort((a, b) => b.amount_usd - a.amount_usd).slice(0, 3).map((i) => i.label).join(', ')
  return {
    items, subtotal, optimistic, buffer,
    setup_min: optimistic, setup_max: buffer,
    note: `Summed from ${items.length} cost line-items (${topItems}${items.length > 3 ? ', more' : ''}). Range = subtotal x0.85 (optimistic) to x1.20 (with contingency buffer).`,
  }
}

function deriveProfitMargin(calc, fp) {
  const rev = calc.revenue ?? {}
  const billing = String(calc.billing_model ?? 'per_unit_daily')
  const avg_bill = Number(rev.avg_bill ?? 0)
  const units_low = Number(rev.units_per_day_low ?? 0)
  const units_high = Number(rev.units_per_day_high ?? 0)
  const driver_label = String(rev.driver_label ?? 'units')
  const monthly = fp.monthly ?? {}
  const cogs_pct = Number(monthly.cogs_pct ?? 40)
  const opex = Number(monthly.opex ?? 0)
  const rev_low = billing === 'subscription_cumulative' ? avg_bill * units_low : avg_bill * units_low * 30
  const rev_high = billing === 'subscription_cumulative' ? avg_bill * units_high : avg_bill * units_high * 30
  const gross_factor = (100 - cogs_pct) / 100
  const gross_low = Math.round(rev_low * gross_factor)
  const gross_high = Math.round(rev_high * gross_factor)
  const profit_min = Math.round(gross_low - opex)
  const profit_max = Math.round(gross_high - opex)
  return {
    formula: 'Profit = Revenue x (1 - COGS%) - Fixed Opex',
    billing_model: billing, avg_bill, units_low, units_high, driver_label,
    rev_low, rev_high, cogs_pct, gross_low, gross_high, opex,
    monthly_profit_min: profit_min, monthly_profit_max: profit_max,
    note: `Revenue calc based on ${billing} model with ${cogs_pct}% COGS and $${opex} monthly opex, yielding $${profit_min}-$${profit_max} net profit.`,
  }
}

function deriveEase(scorecard) {
  const weights = { capital_intensity: 0.25, skill_barrier: 0.2, regulatory_burden: 0.25, operational_complexity: 0.15, time_to_first_revenue: 0.15 }
  const clamp = (n) => Math.min(5, Math.max(1, Math.round(n)))
  const ci = clamp(scorecard.capital_intensity)
  const sb = clamp(scorecard.skill_barrier)
  const rb = clamp(scorecard.regulatory_burden)
  const oc = clamp(scorecard.operational_complexity)
  const tt = clamp(scorecard.time_to_first_revenue)
  const avg = ci * weights.capital_intensity + sb * weights.skill_barrier + rb * weights.regulatory_burden + oc * weights.operational_complexity + tt * weights.time_to_first_revenue
  const ease_score = Math.round((1 - (avg - 1) / 4) * 100)
  const ease = avg <= 2.2 ? 'Easy' : avg <= 3.6 ? 'Moderate' : 'Hard'
  return {
    ease, ease_score,
    effort_scorecard: {
      capital_intensity: ci, skill_barrier: sb, regulatory_burden: rb, operational_complexity: oc, time_to_first_revenue: tt,
      avg: Math.round(avg * 10) / 10, weights, notes: scorecard.notes ?? '',
      note: `${ease} (score ${ease_score}/100). Weighted avg effort = ${avg.toFixed(1)}/5.`,
    },
  }
}

function computeFitIndex(sb) {
  if (!sb || typeof sb !== 'object') return null
  const p = Number(sb.profitability ?? 0), e = Number(sb.ease ?? 0), g = Number(sb.govt_support ?? 0), m = Number(sb.market_momentum ?? 0)
  if (p === 0 && e === 0 && g === 0 && m === 0) return null
  const scale = Math.max(p, e, g, m) > 10 ? 1 : 10
  return Math.min(100, Math.max(0, Math.round((m * scale) * 0.35 + (p * scale) * 0.3 + (e * scale) * 0.2 + (g * scale) * 0.15)))
}

function buildGovtSchemeDetails(schemes) {
  return { schemes: schemes.map((s) => ({ name: s.name ?? '', benefit: s.benefit ?? '', eligibility: s.eligibility ?? '', ministry: s.ministry ?? '', apply_url: s.apply_url ?? s.url ?? null, application_process: s.application_process ?? '' })) }
}

// ---- Prompt: India-only, standard style, full schema incl. the 17 new fields ----

function buildPrompt(titleIdea) {
  const country = 'India'
  const rate = 83.5
  const platforms = 'ShareChat, Moj, Josh, Koo, Telegram groups, LinkedIn India'
  const isDigital = /\b(app|saas|platform|software|digital|online|website|ecommerce|marketplace|fintech|api|subscription|remote)\b/i.test(titleIdea)
  const spaceLoc = isDigital
    ? `"space_location":null,`
    : `"space_location":{"required":true,"type":"retail_front|warehouse|production_unit|shared_space|home_based|kiosk|cart|dark_store","min_sqft":0,"max_sqft":0,"ideal_zone":"str","rent_matrix":[{"tier":"Budget","sqft":0,"monthly_rent_usd":0,"pros":"str","cons":"str"},{"tier":"Mid-range","sqft":0,"monthly_rent_usd":0,"pros":"str","cons":"str"},{"tier":"Premium","sqft":0,"monthly_rent_usd":0,"pros":"str","cons":"str"}],"key_factors":["str","str","str"],"red_flags":["str","str"],"setup_tips":"str"},`

  return `You are PowerProof AI, a ruthlessly execution-focused MSME business intelligence engine, generating a NEW opportunity catalog entry from scratch.

Business idea seed: "${titleIdea}"
Country: India | Currency: INR (Rs, 1 USD = ${rate} INR)

========== CRITICAL RULES ==========
1. ALL financial values = whole USD integers.
2. Schemes/regulations = India ONLY. Real names, real URLs, never placeholders.
3. ${isDigital ? 'space_location: null' : 'space_location: MANDATORY, never null. 3-tier rent matrix.'}
4. demand_trend = EXACTLY 10 points: Jan 2024, Mar 2024, May 2024, Jul 2024, Sep 2024, Nov 2024, Jan 2025, Mar 2025, Jan 2026, Mar 2026.
5. monthly_rev_min/max = REALISTIC first-year solo operator month 3-6.
6. marketing_strategy: min 8 channels incl. UGC, Short-form Reels, Influencer Reach, WhatsApp Flyout, plus local India platforms from: ${platforms}.
7. full_desc = 3 paragraphs: what+money, why NOW in India, first 90 days.
8. score_breakdown: each 0-10, integers, never null.
9. TAM > SAM > SOM (USD millions). SOM = 5-10% of SAM.
10. GOVT SCHEMES: real apply_url, 3-5 schemes minimum.
11. funding_options: 4 types minimum (bootstrap, debt, equity, grant, or revenue_based), real named India sources.
12. risk_matrix: 5 risks minimum across operational/market/regulatory/financial/competitive.
13. unit_economics_deep: whole USD integers.
14. tools_and_stack: 5 tools minimum.
15. effort_scorecard: all scores 1 (very easy) to 5 (very hard). Be honest.
16. setup_cost_breakdown: 5-8 granular line items minimum.
17. pain_points: 3-5 real pains this business solves, severity=critical|high|medium|low.
18. saturation_level: low|medium|high|extreme, be honest not generic.
19. market_verdict: honest verdict on whether this matters RIGHT NOW in India, urgency_score 0-100.
20. future_outlook: honest 3-5 year projection.
21. market_intelligence.swot: 3-4 items each.
22. tags: 8-12 short keyword tags.
23. state_tags: 3-6 Indian states where this business has highest traction.
24. location_tiers: Tier 1/2/3 city suitability, tier_score 1-10.
25. expert_tips_structured: 4-6 hard-won operator tips, short title + 2-3 sentence body.
26. target_customer_pills: 4-8 short segment labels, max 4 words each.

Return ONLY valid compact JSON:
{"title":"str","tagline":"str","full_desc":"str","category_slug":"food-agri|retail|services|manufacturing|digital|education|healthcare|fintech-finance|ev-energy|logistics-mobility|franchise|daily-cashflow|textile","country":"India","monthly_rev_min":0,"monthly_rev_max":0,"payback_months_min":0,"payback_months_max":0,"score_breakdown":{"profitability":0,"ease":0,"govt_support":0,"market_momentum":0},"effort_scorecard":{"capital_intensity":0,"skill_barrier":0,"regulatory_burden":0,"operational_complexity":0,"time_to_first_revenue":0,"notes":"str"},"fit_verdict":"str","saturation_level":"low|medium|high|extreme","saturation_note":"str","pain_points":[{"pain":"str","severity":"critical|high|medium|low","current_workaround":"str","how_this_business_solves_it":"str","willingness_to_pay":"high|medium|low"}],"market_verdict":{"verdict":"bullish|cautious|bearish","urgency_score":0,"timing_note":"str","why_now":["str","str","str"],"why_not_yet":["str"],"verdict_summary":"str"},"future_outlook":{"outlook":"bright|moderate|uncertain|declining","year3_potential":"str","year5_potential":"str","tailwinds":["str","str","str"],"headwinds":["str","str"],"disruption_risk":"low|medium|high","disruption_note":"str","megatrend_alignment":["str"],"future_verdict":"str"},"pros":["s1","s2","s3","s4"],"cons":["s1","s2","s3"],"tags":["tag1","tag2","tag3"],"state_tags":["State1","State2","State3"],"location_tiers":{"tier1":{"tier_score":0,"suitability":"excellent|good|moderate|poor","rationale":"str","best_cities":["City1","City2"],"challenges":"str"},"tier2":{"tier_score":0,"suitability":"excellent|good|moderate|poor","rationale":"str","best_cities":["City1","City2"],"challenges":"str"},"tier3":{"tier_score":0,"suitability":"excellent|good|moderate|poor","rationale":"str","best_cities":["City1","City2"],"challenges":"str"}},"expert_tips_structured":[{"title":"str","body":"str"}],"target_customer_pills":["Segment 1","Segment 2","Segment 3","Segment 4"],"faqs":[{"q":"str","a":"str"}],"headcount":{"min":0,"max":0,"breakdown":[{"role":"str","type":"full_time|part_time|contract","count":0}]},"licenses_required":[{"name":"str","authority":"str","portal":"str","est_cost_usd":0,"est_days":0,"mandatory":true,"process":"online|offline|both","common_issues":"str","description":"str"}],"machinery_list":[{"name":"str","qty":0,"cost_approx":0,"category":"str","mandatory":"Essential|Required|Optional","new_or_used":"New|Either|Used","purpose":"str","sourcing":"str"}],"raw_materials":[{"name":"str","category":"str","cost_per_unit":"str","source":"str","notes":"str","unit":"str","frequency":"Daily|Weekly|Monthly"}],"setup_cost_breakdown":[{"label":"str","amount_usd":0,"notes":"str"}],"financial_projections":{"_unit":"USD","_converted":true,"monthly":{"revenue_low":0,"revenue_high":0,"opex":0,"cogs_pct":0},"assumptions":{"initial_investment":0,"loan_amount":0,"loan_interest_rate_pct":0,"loan_tenure_options":[36,60]},"year3":{"revenue":0,"ebitda":0},"year5":{"revenue":0,"ebitda":0}},"calculator_config":{"billing_model":"per_unit_daily|subscription_cumulative","cogs_label":"str","cogs_editable":true,"cogs_slider_min":0,"cogs_slider_max":0,"revenue":{"avg_bill":0,"units_per_day_low":0,"units_per_day_high":0,"driver_label":"str"},"emi":{"default_loan_amount":0,"interest_rate_pct":0}},"revenue_streams":[{"label":"str","model":"str","pct_of_revenue":0,"avg_ticket_usd":0,"frequency":"str","description":"str","growth_potential":"low|medium|high","dependency":"str","unlock_at":"str"}],"market_demographics":{"market_size_cr":0,"market_cagr":0,"penetration_pct":0,"income_segment":"str","primary_buyers":"str","geography":"str","key_insight":"str","psychographic_profile":"str","buying_triggers":["t1","t2","t3"],"media_consumption":"str","price_sensitivity":"low|medium|high","price_range":"str","decision_timeline":"str","segments":[{"label":"str","pct":0}]},"market_intelligence":{"market_size_unit":"usd_m","cagr_pct":0,"seasonality":"low|medium|high","seasonality_notes":"str","tam_cr":0,"sam_cr":0,"som_cr":0,"market_king":{"name":"str","why":"str","your_path":"str","positioning":"str"},"swot":{"strengths":["s1","s2","s3","s4"],"weaknesses":["w1","w2","w3","w4"],"opportunities":["o1","o2","o3","o4"],"threats":["t1","t2","t3","t4"]},"mvp_weeks_min":0,"mvp_weeks_max":0,"mvp_milestones":["Week 1: str","Week 2-3: str","Week 4: str","Week 6-8: str"],"persona":{"age_range":"str","income_bracket":"str","gender_skew":"male|female|neutral","education":"str","psychographics":"str","pain_points":["p1","p2","p3"],"decision_triggers":["d1","d2","d3"],"channels":["c1","c2","c3"],"jtbd":"str"}},"competitors":{"king_of_market":{"name":"str","why_they_win":"str","their_weakness":"str","your_exploit":"str"},"direct":[{"name":"str","type":"local|national|international","strength":"str","weakness":"str","market_share_est":"str","pricing":"str","not_doing":"str"}],"indirect":[{"name":"str","threat_level":"low|medium|high","reason":"str"}],"your_advantages":["str"],"what_to_do":["str"],"threats":["str"],"badge_context":"str"},"demand_trend":{"label":"str","unit":"Google Trends Index (base 100 = Jan 2024)","data":[{"period":"Jan 2024","value":100},{"period":"Mar 2024","value":0},{"period":"May 2024","value":0},{"period":"Jul 2024","value":0},{"period":"Sep 2024","value":0},{"period":"Nov 2024","value":0},{"period":"Jan 2025","value":0},{"period":"Mar 2025","value":0},{"period":"Jan 2026","value":0},{"period":"Mar 2026","value":0}],"trend_direction":"rising|falling|stable|seasonal","trend_note":"str","peak_period":"str","trough_period":"str"},${spaceLoc}"marketing_strategy":{"total_budget_usd":0,"budget_split":"str","primary_hook":"str","social_proof_angles":["str","str","str"],"psychology_levers":[{"lever":"str","application":"str"}],"budget_milestones":{"month_1":{"total_usd":0,"focus":"Aggressive launch","channels":[{"name":"str","budget_usd":0,"action":"str"}]},"month_6":{"total_usd":0,"focus":"Conversion","channels":[{"name":"str","budget_usd":0,"action":"str"}]},"month_12":{"total_usd":0,"focus":"Retention","channels":[{"name":"str","budget_usd":0,"action":"str"}]},"month_18":{"total_usd":0,"focus":"Loyalty","channels":[{"name":"str","budget_usd":0,"action":"str"}]}},"channels":[{"name":"str","type":"str","budget_usd":0,"priority":"primary","rationale":"str","platform_setup":"str","ad_creative_idea":"str","tactics":["str"],"dos":["str"],"donts":["str"],"success_rate":"high","failure_mode":"str","timeline":"str","kpi":"str"}],"guerrilla_play":{"idea":"str","execution":"str","expected_impact":"str"},"launch_sequence":[{"week":"Week 1","action":"str","goal":"str"}],"retention_strategy":"str","referral_mechanic":"str"},"govt_schemes":[{"name":"str","benefit":"str","eligibility":"str","apply_url":"https://official-url","ministry":"str","application_process":"str"}],"funding_options":{"summary":"str","options":[{"type":"bootstrap|debt|equity|grant|revenue_based","label":"str","source_name":"str","amount_range_usd_min":0,"amount_range_usd_max":0,"when_to_apply":"str","interest_or_dilution":"str","approval_timeline":"str","eligibility_bar":"low|medium|high","pros":["str"],"cons":["str"],"url":"https://real-url","best_for":"str"}]},"risk_matrix":{"overall_risk":"low|medium|high","risks":[{"category":"operational|market|regulatory|financial|competitive","risk":"str","description":"str","probability":"low|medium|high","impact":"low|medium|high","risk_score":"low|medium|high|critical","mitigation":"str","early_warning_sign":"str"}]},"unit_economics_deep":{"cac_by_channel":[{"channel":"str","cac_usd":0,"notes":"str"}],"avg_ltv_usd":0,"ltv_cac_ratio":0,"gross_margin_pct":0,"contribution_margin_usd":0,"break_even_units_per_month":0,"break_even_revenue_usd":0,"payback_period_months":0,"notes":"str"},"tools_and_stack":[{"category":"str","name":"str","purpose":"str","cost_usd_per_month":0,"free_tier_available":true,"priority":"must_have|nice_to_have","url":"https://tool-url","notes":"str"}]}`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')
  const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
  const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')
  const PLATFORM_GEMINI_KEY = Deno.env.get('GEMINI_API_KEY')

  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY || !SUPABASE_ANON_KEY || !PLATFORM_GEMINI_KEY) {
    return json({ error: 'Server misconfigured' }, 500)
  }

  // Admin gate: same pattern as admin-opportunity-audit
  const authHeader = req.headers.get('Authorization')
  if (!authHeader) return json({ error: 'Unauthorized' }, 401)
  const token = authHeader.replace(/^Bearer\s+/i, '')
  const { data: { user }, error: authErr } = await createClient(SUPABASE_URL, SUPABASE_ANON_KEY).auth.getUser(token)
  if (authErr || !user) return json({ error: 'Unauthorized' }, 401)

  const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)
  const { data: prof } = await admin.from('profiles').select('role').eq('id', user.id).maybeSingle()
  const role = String(prof?.role ?? '').toLowerCase()
  if (!['admin', 'super_admin', 'super-admin'].includes(role)) {
    return json({ error: 'Forbidden' }, 403)
  }

  const byokKey = req.headers.get('x-gemini-key')?.trim() || null
  const geminiKey = byokKey ?? PLATFORM_GEMINI_KEY

  let body
  try { body = await req.json() } catch { return json({ error: 'Invalid JSON body' }, 400) }

  const titleIdea = String(body?.title_idea ?? '').trim()
  if (!titleIdea) return json({ error: 'title_idea is required' }, 400)

  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), GEMINI_TIMEOUT_MS)
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${geminiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal: controller.signal,
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: buildPrompt(titleIdea) }] }],
          generationConfig: { temperature: 0.7, maxOutputTokens: 200000, responseMimeType: 'application/json' },
          safetySettings: [
            { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
            { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
            { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
            { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
          ],
        }),
      }
    )
    clearTimeout(timeout)
    if (!res.ok) {
      const t = await res.text()
      return json({ error: `Gemini ${res.status}: ${t}` }, 502)
    }
    const d = await res.json()
    const text = d.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
    if (!text) return json({ error: 'Empty Gemini response' }, 502)

    const parsed = JSON.parse(strip(text))

    // Derived fields
    let setup_min = 0, setup_max = 0, setupCostDerivation = { note: 'Fallback' }
    try {
      const rb = parsed.setup_cost_breakdown ?? []
      if (rb.length > 0) {
        const dd = deriveSetupCost(rb)
        setup_min = dd.setup_min; setup_max = dd.setup_max
        const { setup_min: _a, setup_max: _b, ...meta } = dd
        setupCostDerivation = meta
      }
    } catch (e) { console.warn('[admin-create-v2] deriveSetupCost failed:', String(e)) }

    let monthly_profit_min = 0, monthly_profit_max = 0, profitDerivation = { note: 'Fallback' }
    try {
      const cc = parsed.calculator_config ?? {}
      const fpm = parsed.financial_projections?.monthly ?? {}
      if (cc.revenue && fpm.cogs_pct !== undefined) {
        const dd = deriveProfitMargin(cc, { monthly: fpm })
        monthly_profit_min = dd.monthly_profit_min; monthly_profit_max = dd.monthly_profit_max
        const { monthly_profit_min: _a, monthly_profit_max: _b, ...meta } = dd
        profitDerivation = meta
      }
    } catch (e) { console.warn('[admin-create-v2] deriveProfitMargin failed:', String(e)) }

    let ease = 'Moderate', easeScore = 50, effortScorecard = { note: 'Fallback' }
    try {
      const sc = parsed.effort_scorecard
      if (sc && typeof sc.capital_intensity === 'number') {
        const dd = deriveEase(sc)
        ease = dd.ease; easeScore = dd.ease_score; effortScorecard = dd.effort_scorecard
      }
    } catch (e) { console.warn('[admin-create-v2] deriveEase failed:', String(e)) }

    let fitIndex = null
    try { fitIndex = computeFitIndex(parsed.score_breakdown) }
    catch (e) { console.warn('[admin-create-v2] computeFitIndex failed:', String(e)) }

    let govtSchemeDetails = { schemes: [] }
    try { govtSchemeDetails = buildGovtSchemeDetails(parsed.govt_schemes ?? []) }
    catch (e) { console.warn('[admin-create-v2] buildGovtSchemeDetails failed:', String(e)) }

    const satLevel = parsed.saturation_level ?? null
    const isSat = satLevel ? (satLevel === 'extreme' || satLevel === 'high') : false
    const slug = `${slugify(parsed.title || titleIdea)}-${Date.now().toString(36)}`

    if (parsed.market_intelligence && typeof parsed.market_intelligence === 'object') {
      parsed.market_intelligence.market_size_unit = 'usd_m'
    }

    const insertPayload = {
      slug, title: parsed.title, tagline: parsed.tagline, full_desc: parsed.full_desc, short_desc: (parsed.tagline || '').slice(0, 200),
      category_slug: parsed.category_slug, country: 'India', source: 'india', status: 'live',
      monthly_rev_min: parsed.monthly_rev_min, monthly_rev_max: parsed.monthly_rev_max,
      monthly_profit_min, monthly_profit_max, profit_derivation: profitDerivation,
      setup_min, setup_max, setup_cost_derivation: setupCostDerivation,
      payback_months_min: parsed.payback_months_min, payback_months_max: parsed.payback_months_max,
      score_breakdown: parsed.score_breakdown, fit_index: fitIndex, fit_verdict: parsed.fit_verdict ?? null,
      ease, ease_score: easeScore, effort_scorecard: effortScorecard,
      pros: parsed.pros, cons: parsed.cons,
      tags: parsed.tags ?? null, state_tags: parsed.state_tags ?? null, location_tiers: parsed.location_tiers ?? null,
      expert_tips_structured: parsed.expert_tips_structured ?? null, target_customer_pills: parsed.target_customer_pills ?? null,
      is_saturated: isSat, saturation_level: satLevel, saturation_note: parsed.saturation_note ?? null,
      pain_points: parsed.pain_points ?? null, market_verdict: parsed.market_verdict ?? null, future_outlook: parsed.future_outlook ?? null,
      faqs: parsed.faqs, headcount: parsed.headcount, licenses_required: parsed.licenses_required, machinery_list: parsed.machinery_list,
      raw_materials: parsed.raw_materials, setup_cost_breakdown: parsed.setup_cost_breakdown,
      financial_projections: parsed.financial_projections, calculator_config: parsed.calculator_config,
      revenue_streams: parsed.revenue_streams, market_demographics: parsed.market_demographics, market_intelligence: parsed.market_intelligence,
      competitors: parsed.competitors, demand_trend: parsed.demand_trend, space_location: parsed.space_location ?? null,
      marketing_strategy: parsed.marketing_strategy, govt_schemes: parsed.govt_schemes, govt_scheme_details: govtSchemeDetails,
      funding_options: parsed.funding_options ?? null, risk_matrix: parsed.risk_matrix ?? null,
      unit_economics_deep: parsed.unit_economics_deep ?? null, tools_and_stack: parsed.tools_and_stack ?? null,
      research_style: 'standard', style_addons: null,
      created_by: user.id, updated_at: new Date().toISOString(),
    }

    const { data: inserted, error: insertErr } = await admin.from('opportunities').insert(insertPayload).select('id, slug, title').single()
    if (insertErr || !inserted) {
      return json({ error: `Insert failed: ${insertErr?.message}` }, 500)
    }

    // Score depends on live engagement data — compute once now so the row isn't
    // sitting with a null score, understanding it will read as low until real
    // views/saves accrue (30% of the formula is 7-day engagement, 15% velocity).
    let computedScore = null
    try {
      const { data: scoreResult } = await admin.rpc('compute_opportunity_score', { opp_id: inserted.id })
      computedScore = scoreResult ?? null
    } catch (e) {
      console.warn('[admin-create-v2] compute_opportunity_score failed (non-fatal):', String(e))
    }

    return json({
      success: true,
      id: inserted.id,
      slug: inserted.slug,
      title: inserted.title,
      score: computedScore,
      note: computedScore !== null
        ? `Score computed: ${computedScore}. Note this will look low initially — 30% of the formula is 7-day platform engagement and 15% is week-over-week velocity, both zero for a brand-new row.`
        : 'Score computation failed — check logs, row was still inserted successfully.',
    })
  } catch (e) {
    return json({ error: String(e) }, 500)
  }
})
